#!/usr/bin/env bash
NAME="SzczygielPiotr"
if [ -d "$1" ]; then
    find "$1" -maxdepth 1 -type d -exec make -C {} clean \;
    mkdir "$NAME"
    cp -r "$1" "$NAME"
    tar zcvf "$NAME-$1.tar.gz" "$NAME"
    rm -r "$NAME"
else
    echo "'$1' doesn't exist"
fi
